/**
 * Product screenshots for the marketing site, captured from the real app's
 * demo businesses by `e2e/marketing-shots/capture.ts` (plan U20). Generated:
 * edit `e2e/marketing-shots/shots.config.ts` and re-run the capture instead.
 * `width` and `height` are the image's pixels (2× the CSS layout).
 * `content/shots.ts` reads this: a captured shot replaces the placeholder.
 * Help's `help-…` shots are read by `content/help` articles; `mark` is
 * where the step's control sits, in fractions of the image.
 */
export const CAPTURED: Record<
    string,
    {
        src: string;
        alt: string;
        width: number;
        height: number;
        mark?: { x: number; y: number; w: number; h: number };
    }
> = {
    "s-home": {
        src: "/shots/v2/s-home.webp",
        alt: "Home at Rye & Co. (demo bakery): what needs doing today, from late orders to a failed renewal",
        width: 2880,
        height: 1800,
    },
    "s-orders": {
        src: "/shots/v2/s-orders.webp",
        alt: "The Orders list at Rye & Co. (demo bakery): each order's step, how long it has waited, when it was placed and its total",
        width: 2880,
        height: 1800,
    },
    "r-order": {
        src: "/shots/v2/r-order.webp",
        alt: "An order at Rye & Co. (demo bakery): how long it has waited, a sesame allergy warning, items, customer and money",
        width: 2880,
        height: 1800,
    },
    "r-invoice": {
        src: "/shots/v2/r-invoice.webp",
        alt: "A GST tax invoice from Rye & Co. (demo bakery) to a café, with the business's details and tax",
        width: 2880,
        height: 1800,
    },
    "r-customers": {
        src: "/shots/v2/r-customers.webp",
        alt: "The Customers list: each customer with tags, last order, orders and spend",
        width: 2880,
        height: 1800,
    },
    "s-customer": {
        src: "/shots/v2/s-customer.webp",
        alt: "Priya Raman's page: her orders and spend, a sesame allergy and what she usually buys",
        width: 2880,
        height: 1800,
    },
    "r-subdetail": {
        src: "/shots/v2/r-subdetail.webp",
        alt: "Priya Raman's weekly loaf: next charge, upcoming collections, plan and changes",
        width: 2880,
        height: 1800,
    },
    "s-subs": {
        src: "/shots/v2/s-subs.webp",
        alt: "Subscriptions at Rye & Co. (demo bakery) with one failed renewal flagged",
        width: 2880,
        height: 1800,
    },
    "s-billing": {
        src: "/shots/v2/s-billing.webp",
        alt: "Invoices at Rye & Co. (demo bakery): each order's GST invoice, paid or due, with what's overdue flagged",
        width: 2880,
        height: 1800,
    },
    "r-calendar": {
        src: "/shots/v2/r-calendar.webp",
        alt: "This month on the calendar with each day's money and a strip of totals",
        width: 2880,
        height: 1800,
    },
    "p-products": {
        src: "/shots/v2/p-products.webp",
        alt: "The Products list at Rye & Co. (demo bakery): what needs restocking at the top, then every product with status, stock and price",
        width: 2880,
        height: 1800,
    },
    "p-editor": {
        src: "/shots/v2/p-editor.webp",
        alt: "The product editor: name, link, price and category beside visibility, variants and stock",
        width: 2880,
        height: 1800,
    },
    "p-site": {
        src: "/shots/v2/p-site.webp",
        alt: "The shop page of Rye & Co. (demo bakery) for the Sourdough loaf: sizes, price and Add to basket",
        width: 2228,
        height: 2406,
    },
    "p-stock": {
        src: "/shots/v2/p-stock.webp",
        alt: "Stock levels for each size at Hill Road and Online, with what can be sold and what's promised",
        width: 2880,
        height: 1800,
    },
    "p-detail": {
        src: "/shots/v2/p-detail.webp",
        alt: "Sourdough loaf's page: what can be sold now, with open orders, discounts, collections, the website and reviews",
        width: 2880,
        height: 1800,
    },
    "s-insights": {
        src: "/shots/v2/s-insights.webp",
        alt: "Insights: site views, visitors, enquiries and orders over the last 30 days, with views by day and top pages",
        width: 2880,
        height: 1800,
    },
    "i-compare": {
        src: "/shots/v2/i-compare.webp",
        alt: "Insights for 30 days: site views, unique visitors, enquiries and orders, views by day and the most-viewed pages",
        width: 2340,
        height: 1838,
    },
    "i-weeks": {
        src: "/shots/v2/i-weeks.webp",
        alt: "Ninety days of site views, a bar for each day",
        width: 2340,
        height: 632,
    },
    "i-store": {
        src: "/shots/v2/i-store.webp",
        alt: "Insights for the last seven days: site views, enquiries, orders and the most-viewed pages",
        width: 2880,
        height: 1800,
    },
    "g-home": {
        src: "/shots/v2/g-home.webp",
        alt: "Home at Pulse Fitness (demo gym): overdue memberships, follow-ups and this week's takings",
        width: 2880,
        height: 1800,
    },
    "g-bookings": {
        src: "/shots/v2/g-bookings.webp",
        alt: "The week at Pulse Fitness (demo gym): personal training and classes, by the hour",
        width: 2880,
        height: 1800,
    },
    "g-book": {
        src: "/shots/v2/g-book.webp",
        alt: "The booking page of Pulse Fitness (demo gym), with services, classes and a summary",
        width: 2880,
        height: 1800,
    },
    "g-courses": {
        src: "/shots/v2/g-courses.webp",
        alt: "Courses at Pulse Fitness (demo gym): a four-week strength course with the places taken",
        width: 2880,
        height: 1800,
    },
    "g-packs": {
        src: "/shots/v2/g-packs.webp",
        alt: "Class packs: 5 and 10 classes with how many are sold and still to use",
        width: 2880,
        height: 1800,
    },
    "g-customer": {
        src: "/shots/v2/g-customer.webp",
        alt: "Asha Verma's page at Pulse Fitness (demo gym): classes left on her membership and her next booking",
        width: 2880,
        height: 1800,
    },
    "g-subs": {
        src: "/shots/v2/g-subs.webp",
        alt: "Memberships at Pulse Fitness (demo gym) with their next charge",
        width: 2880,
        height: 1800,
    },
    "g-billing": {
        src: "/shots/v2/g-billing.webp",
        alt: "Invoices at Pulse Fitness (demo gym), with the overdue ones flagged",
        width: 2880,
        height: 1800,
    },
    "g-site": {
        src: "/shots/v2/g-site.webp",
        alt: "The site of Pulse Fitness (demo gym): what's on today and Book a free trial",
        width: 2880,
        height: 1800,
    },
    "d-home": {
        src: "/shots/v2/d-home.webp",
        alt: "Home at Kavi Dental (demo clinic): a patient's note from the booking page, overdue bills and the week so far",
        width: 2880,
        height: 1800,
    },
    "d-order": {
        src: "/shots/v2/d-order.webp",
        alt: "A root canal at Kavi Dental (demo clinic): visit 1 attended, visit 2 booked, visit 3 still to book",
        width: 2880,
        height: 1800,
    },
    "d-customer": {
        src: "/shots/v2/d-customer.webp",
        alt: "Rahul Verma's page with a note from the booking page about a new blood-pressure tablet",
        width: 2880,
        height: 1800,
    },
    "d-customers": {
        src: "/shots/v2/d-customers.webp",
        alt: "Patients at Kavi Dental (demo clinic), with medical and allergy tags",
        width: 2880,
        height: 1800,
    },
    "d-book": {
        src: "/shots/v2/d-book.webp",
        alt: "The booking page of Kavi Dental (demo clinic), with check-ups, a root canal over three visits and a video consult",
        width: 2880,
        height: 1800,
    },
    "d-billing": {
        src: "/shots/v2/d-billing.webp",
        alt: "Bills of supply at Kavi Dental (demo clinic), with the overdue ones flagged",
        width: 2880,
        height: 1800,
    },
    "d-site": {
        src: "/shots/v2/d-site.webp",
        alt: "The site of Kavi Dental (demo clinic): free times today and Book an appointment",
        width: 2880,
        height: 1800,
    },
    "help-add-product-1": {
        src: "/shots/help/help-add-product-1.webp",
        alt: "Products at Rye & Co. (demo bakery), with New product open on its two locations, Online and Hill Road",
        width: 2048,
        height: 1120,
        mark: { x: 0.8128, y: 0.1821, w: 0.1676, h: 0.0893 },
    },
    "help-add-product-2": {
        src: "/shots/help/help-add-product-2.webp",
        alt: "Basics for a new product at Rye & Co. (demo bakery): the name, the address on the shop made from it, the price and the category",
        width: 1070,
        height: 1240,
        mark: { x: 0.0467, y: 0.2944, w: 0.9065, h: 0.0851 },
    },
    "help-add-product-3": {
        src: "/shots/help/help-add-product-3.webp",
        alt: "Photos and videos for the Sourdough loaf at Rye & Co. (demo bakery): two photos, the first marked Cover, each with what it shows",
        width: 1070,
        height: 1058,
        mark: { x: 0.0598, y: 0.2385, w: 0.107, h: 0.0576 },
    },
    "help-add-product-4": {
        src: "/shots/help/help-add-product-4.webp",
        alt: "A new product at Rye & Co. (demo bakery) with a name and a price, Visibility set to Draft and the Create draft button",
        width: 2048,
        height: 1120,
        mark: { x: 0.8818, y: 0.1143, w: 0.1104, h: 0.0821 },
    },
    "help-add-product-5": {
        src: "/shots/help/help-add-product-5.webp",
        alt: "Variants and Stock for the Sourdough loaf at Rye & Co. (demo bakery): 800g and 400g with their own SKU and price, and Track stock on with On hand and Warn at for each",
        width: 948,
        height: 1616,
        mark: { x: 0.846, y: 0.6027, w: 0.1013, h: 0.042 },
    },
    "help-create-business-1": {
        src: "/shots/help/help-create-business-1.webp",
        alt: "Make your account on Saroh: your name, email and password, and the Send the code button",
        width: 792,
        height: 726,
        mark: { x: 0.0152, y: 0.8403, w: 0.9697, h: 0.1431 },
    },
    "help-create-business-2": {
        src: "/shots/help/help-create-business-2.webp",
        alt: "Set up Saroh, asking what you are setting up: a business, just me, or a site for my work",
        width: 808,
        height: 756,
        mark: { x: 0.0248, y: 0.111, w: 0.9505, h: 0.2048 },
    },
    "help-create-business-3": {
        src: "/shots/help/help-create-business-3.webp",
        alt: "Setting up Tulsi Florist (a demo florist): its name, and its address on Saroh, tulsi-florist.saroh.app, marked free",
        width: 808,
        height: 634,
        mark: { x: 0.0248, y: 0.5678, w: 0.9505, h: 0.1577 },
    },
    "help-create-business-4": {
        src: "/shots/help/help-create-business-4.webp",
        alt: "Setting up Tulsi Florist (a demo florist): Not registered chosen, India as where it trades, and the Create the business button",
        width: 808,
        height: 928,
        mark: { x: 0.0248, y: 0.8665, w: 0.9505, h: 0.1119 },
    },
    "help-create-business-5": {
        src: "/shots/help/help-create-business-5.webp",
        alt: "Home at Asha's Bakery (demo bakery), new and with nothing on yet: What will you do first?, with Turn on Sell open",
        width: 2048,
        height: 1120,
        mark: { x: 0.9044, y: 0.9, w: 0.0839, h: 0.0893 },
    },
    "help-add-gstin-1": {
        src: "/shots/help/help-add-gstin-1.webp",
        alt: "Settings, Business, Tax and invoices at Northwind Supply (demo shop): not GST-registered yet, with the Edit button",
        width: 2048,
        height: 1120,
        mark: { x: 0.9011, y: 0.651, w: 0.0608, h: 0.0786 },
    },
    "help-add-gstin-2": {
        src: "/shots/help/help-add-gstin-2.webp",
        alt: "Northwind Supply (demo shop) with GST-registered switched on and a GSTIN typed, its state code, PAN, entity, Z and check character shown under it",
        width: 1496,
        height: 468,
        mark: { x: 0.0107, y: 0.4498, w: 0.9786, h: 0.2137 },
    },
    "help-add-gstin-3": {
        src: "/shots/help/help-add-gstin-3.webp",
        alt: "The Registered address tab at Northwind Supply (demo shop): the address, city, PIN and state printed under the legal name",
        width: 2048,
        height: 1120,
        mark: { x: 0.6804, y: 0.509, w: 0.1663, h: 0.0946 },
    },
    "help-add-gstin-4": {
        src: "/shots/help/help-add-gstin-4.webp",
        alt: "How it prints at Northwind Supply (demo shop), showing the unsaved edit: a tax invoice with the GSTIN and Karnataka",
        width: 688,
        height: 646,
        mark: { x: 0.0727, y: 0.1594, w: 0.2659, h: 0.0859 },
    },
    "help-add-gstin-5": {
        src: "/shots/help/help-add-gstin-5.webp",
        alt: "Ready to take payments at Northwind Supply (demo shop): Choose your business type, with the Choose type button",
        width: 1376,
        height: 366,
        mark: { x: 0.7975, y: 0.3365, w: 0.1691, h: 0.2393 },
    },
    "help-take-order-1": {
        src: "/shots/help/help-take-order-1.webp",
        alt: "Orders at Northwind Supply (demo shop), with the New order button",
        width: 2048,
        height: 1120,
        mark: { x: 0.7641, y: 0.225, w: 0.132, h: 0.0893 },
    },
    "help-take-order-2": {
        src: "/shots/help/help-take-order-2.webp",
        alt: "New order at Northwind Supply (demo shop): taken at the store, Meera Iyer picked as the customer, and a hi-vis vest added",
        width: 1120,
        height: 1800,
        mark: { x: 0.05, y: 0.2133, w: 0.7591, h: 0.0367 },
    },
    "help-take-order-3": {
        src: "/shots/help/help-take-order-3.webp",
        alt: "New order at Northwind Supply (demo shop): local delivery to an address, UPI at the counter, and the UPI received, create button",
        width: 1120,
        height: 1800,
        mark: { x: 0.0232, y: 0.9289, w: 0.9554, h: 0.0644 },
    },
    "help-take-order-4": {
        src: "/shots/help/help-take-order-4.webp",
        alt: "Order #ORD-004 at Northwind Supply (demo shop): a pick-up order at Ready, with the Mark collected button",
        width: 2048,
        height: 1120,
        mark: { x: 0.8409, y: 0.2228, w: 0.1416, h: 0.0893 },
    },
    "help-take-order-5": {
        src: "/shots/help/help-take-order-5.webp",
        alt: "Order #ORD-002 at Northwind Supply (demo shop), not paid yet, with the Paid in cash button",
        width: 2048,
        height: 1120,
        mark: { x: 0.8444, y: 0.4049, w: 0.1214, h: 0.0893 },
    },
    "help-take-order-6": {
        src: "/shots/help/help-take-order-6.webp",
        alt: "Orders at Northwind Supply (demo shop), with All locations open on its two locations, Northwind Supply Store and Online",
        width: 2048,
        height: 1120,
        mark: { x: 0.416, y: 0.4098, w: 0.1568, h: 0.0893 },
    },
    "help-connect-razorpay-1": {
        src: "/shots/help/help-connect-razorpay-1.webp",
        alt: "Settings, Providers at Northwind Supply (demo shop): Razorpay disconnected, with its Connect button",
        width: 2048,
        height: 1120,
        mark: { x: 0.8735, y: 0.5806, w: 0.0884, h: 0.0786 },
    },
    "help-connect-razorpay-2": {
        src: "/shots/help/help-connect-razorpay-2.webp",
        alt: "Connecting Razorpay at Northwind Supply (demo shop): Key ID (public) and Key secret filled in",
        width: 988,
        height: 310,
        mark: { x: 0.0121, y: 0.3615, w: 0.4879, h: 0.3213 },
    },
    "help-connect-razorpay-3": {
        src: "/shots/help/help-connect-razorpay-3.webp",
        alt: "Connecting Razorpay at Northwind Supply (demo shop): the webhook URL to copy, and the five events to tick",
        width: 988,
        height: 626,
        mark: { x: 0.8135, y: 0.4752, w: 0.1743, h: 0.1404 },
    },
    "help-connect-razorpay-4": {
        src: "/shots/help/help-connect-razorpay-4.webp",
        alt: "Connecting Razorpay at Northwind Supply (demo shop): a webhook signing secret generated, and the Connect Razorpay button",
        width: 988,
        height: 444,
        mark: { x: 0.6501, y: 0.748, w: 0.3378, h: 0.225 },
    },
    "help-connect-cashfree-1": {
        src: "/shots/help/help-connect-cashfree-1.webp",
        alt: "Settings, Providers at Rye & Co. (demo bakery): Cashfree under Available, with its Connect button",
        width: 2048,
        height: 1120,
        mark: { x: 0.8735, y: 0.7467, w: 0.0884, h: 0.0786 },
    },
    "help-connect-cashfree-2": {
        src: "/shots/help/help-connect-cashfree-2.webp",
        alt: "Connecting Cashfree at Rye & Co. (demo bakery): Key ID and Key secret filled in, and the optional Public key",
        width: 988,
        height: 404,
        mark: { x: 0.0121, y: 0.2772, w: 0.4879, h: 0.2464 },
    },
    "help-connect-cashfree-3": {
        src: "/shots/help/help-connect-cashfree-3.webp",
        alt: "Connecting Cashfree at Rye & Co. (demo bakery): the webhook URL to copy, and the four events to tick",
        width: 988,
        height: 538,
        mark: { x: 0.8135, y: 0.3909, w: 0.1743, h: 0.163 },
    },
    "help-connect-cashfree-4": {
        src: "/shots/help/help-connect-cashfree-4.webp",
        alt: "Connecting Cashfree at Rye & Co. (demo bakery): no separate secret to add, and the Connect Cashfree button",
        width: 988,
        height: 222,
        mark: { x: 0.6543, y: 0.4971, w: 0.3335, h: 0.4491 },
    },
    "help-connect-cashfree-5": {
        src: "/shots/help/help-connect-cashfree-5.webp",
        alt: "Settings, Providers at Northwind Supply (demo shop): Cashfree connected, with no payment updates received yet",
        width: 2048,
        height: 1120,
        mark: { x: 0.3818, y: 0.4392, w: 0.2206, h: 0.0835 },
    },
};
