# Optional, always. Saroh is free under the Elastic License 2.0 and no feature,
# fix or answer is ever gated behind sponsorship — see the Licence section of
# README.md. This exists only for people who have asked how to put something
# back.
github: [hiyashmehta]
