import "@saroh/ui/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const fontSans = localFont({
    src: "../../../packages/ui/fonts/Geist-latin.woff2",
    display: "swap",
    variable: "--font-sans",
});

const fontDisplay = localFont({
    src: "../../../packages/ui/fonts/BricolageGrotesque-latin.woff2",
    display: "swap",
    variable: "--font-display",
});

export const metadata: Metadata = {
    title: "Saroh app",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        // `data-skin="mono"` pins the pre-brand register. This app renders
        // merchants' sites, which carry their own `--site-*` themes; the few
        // Saroh-drawn surfaces here (404, error, checkout chrome) stay as they
        // were rather than taking Saroh's Ink & Saffron onto someone else's shop.
        <html lang="en" data-skin="mono">
            <body
                className={`${fontSans.variable} ${fontDisplay.variable} font-sans`}
            >
                {children}
            </body>
        </html>
    );
}
